-- Simple example of creating an autocommand in Neovim using Lua
-- vim.api.nvim_create_autocmd('BufWritePost', {
--   pattern = '*',
--   callback = function()
--     print 'File saved! 🥳'
--   end,
-- })
